### ISSUE TITLE
kernel folder

### ISSUE THREAD

**Issue by sajadd3869** [MGeurts/laravel-9-bootstrap-5#1]
hi. I cloned this project and after I run "php artisan serve" the error occurred that vendor and autoload not find
after that I run "composer install" to download dependencies
after that I run "php artisan serve" bot error shown that Kernel folder didn't find in App\ directoryr.
all laravel projects have kernel directory in App\ that handle artisan command and etc.
Where are the kernel??!

**Comment by MGeurts** [comment]
Hi,

You should learn how to clone & install repositories.

You can follow the documentation on https://www.kreaweb.be/laravel-8-bootstrap-5/#2_LARAVEL_9_-_Build_the_application_by_cloning_the_GitHub_repository/  

Kind regards.

Kreaweb
